name: mstest-integration

permissions:
  contents: read

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-and-test: 
        name: mstest-integration
        runs-on: ubuntu-latest
        env:
            Parameters__RedisPassword: "testPassword"
            Parameters__DevServerPassword: "testPassword"
            Parameters__KeycloakPassword: "testPassword"
            Parameters__KeycloakUsername: "testUsername"
            Parameters__HashicorpVaultToken: "testToken"

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0
            
            - name: Create Keycloak certs directory
              run: |
                mkdir -p ./resources/keycloak/certs
                openssl req -newkey rsa:2048 -nodes -keyout ./resources/keycloak/certs/localhost-key.pem -x509 -days 365 -out ./resources/keycloak/certs/localhost.pem -subj "/CN=localhost"

            - name: Restore Dependencies
              run: dotnet restore
            
            - name: Build Solution
              run: dotnet build --no-restore

            - name: Run Tests
              run: dotnet test --no-build --verbosity normal